dist: trusty
sudo: required
language: cpp
cache: ccache
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
    - xorg-dev
    - libglu1-mesa-dev
    - libsuitesparse-dev
  homebrew:
    packages:
    - libgmp
    - ccache
matrix:
  include:
  - os: linux
    compiler: gcc-7
    env:
    - MATRIX_EVAL="export CC=gcc-7 && CXX=g++-7 && CONFIG=Debug"
  # - os: osx
  #   osx_image: xcode8.3
  #   compiler: clang
  #   env:
  #   - MATRIX_EVAL="export CONFIG=Debug"
  # - os: osx
  #   osx_image: xcode9.4
  #   compiler: clang
  #   env:
  #   - MATRIX_EVAL="export CONFIG=Debug"
  - os: osx
    osx_image: xcode10.2
    compiler: clang
    env:
    - MATRIX_EVAL="export CONFIG=Debug"

install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
- eval "${MATRIX_EVAL}"
- ccache --max-size=5.0G
- ccache -V && ccache --show-stats && ccache --zero-stats

script:
- git clone https://github.com/wildmeshing/data.git
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=$CONFIG ..
- make -j2
- ls ../
- ./TriWild --input ../data/rocket.obj
- ./TriWild --input ../data/rocket.obj --feature-input ../data/rocket.json
- ccache --show-stats
- cd ..
